version: '3.9'
services:
  db:
    container_name: postgres-soap
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data-postgres/:/var/lib/postgres
  pgadmin:
    container_name: pgadmin4-soap
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
networks:
  default:
    driver: bridge
    name: app